# Generated by Django 6.0.3 on 2026-03-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchlog',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
